### ISSUE TITLE
Complete Berlin region is not working 

### ISSUE THREAD

**Issue by JonasCir** [healthIMIS/aha-kompass#2]
Surrounding areas appear to work just fine, however, selecting any district of Berlin triggers an error message. Fails both for IOS and Android.

---
![fail](https://user-images.githubusercontent.com/20031875/115226059-14c57b80-a10f-11eb-8107-cbb5db94900c.jpeg)
---
![works](https://user-images.githubusercontent.com/20031875/115226056-14c57b80-a10f-11eb-8a18-9a952790c36d.jpeg)

**Comment by TheJKM** [comment]
The new backend does not divide Berlin into sub-countys, so we run into a 404. Fix will come soon
